-- KASOWANIE TABEL
DROP TABLE Users CASCADE CONSTRAINTS;
DROP TABLE Levels CASCADE CONSTRAINTS;
DROP TABLE Categories CASCADE CONSTRAINTS;
DROP TABLE Realisations CASCADE CONSTRAINTS;
DROP TABLE Words CASCADE CONSTRAINTS;
DROP TABLE Courses CASCADE CONSTRAINTS;
DROP TABLE Courses_Categories CASCADE CONSTRAINTS;
DROP TABLE Words_Categories CASCADE CONSTRAINTS;
DROP TABLE Words_Realisations CASCADE CONSTRAINTS;

-- KASOWANIE SEKWENCJI
DROP SEQUENCE seq_user;
DROP SEQUENCE seq_level;
DROP SEQUENCE seq_category;
DROP SEQUENCE seq_course;
DROP SEQUENCE seq_realisation;
DROP SEQUENCE seq_word;

commit;